# Cloudflare Worker configuration for Supabase integration
name = "brother-points-supabase"
main = "worker-supabase.js"
compatibility_date = "2024-01-01"

[env.production]
name = "brother-points-supabase"

# Environment variables for Supabase
[env.production.vars]
SUPABASE_URL = "YOUR_SUPABASE_URL"
SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY"

# Add your custom domain here
# routes = [
#   { pattern = "points-api.joshi1.com/*", zone_name = "joshi1.com" }
# ]

# KV storage for caching (optional)
# [[kv_namespaces]]
# binding = "POINTS_CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"
